Мирута Наталія Романівна
ФІТ 3-15
Варіант 8
Була присутня на парі

In [99]:
#!pip install numpy

In [100]:
import numpy as np

In [101]:
np.__version__

'2.0.2'

1.Створити матрицю 3*3, заповнити її цілими числами від 1 до 5

In [102]:
matrix = np.random.randint(1, 6, size=(3, 3))
matrix

array([[1, 1, 2],
       [2, 2, 2],
       [4, 5, 4]])

2. Обчислити визначник матриці

In [103]:
det = np.linalg.det(matrix)
det

np.float64(2.0)

3. Знайти добуток всіх елементів матриці

In [104]:
product = np.prod(matrix)
product

np.int64(1280)

In [105]:
prod_1 = np.prod(matrix[0])
prod_2 = np.prod(matrix[1])
prod_3 = np.prod(matrix[2])
prod_1*prod_2*prod_3

np.int64(1280)

4. Знайти суму всіх елементів матриці

In [106]:
np.sum(matrix)


np.int64(23)

5. Обчислити найбільший, найменший елементи

In [107]:
np.max(matrix)


np.int64(5)

In [108]:
np.min(matrix)


np.int64(1)

6. Знайти середнє значення елементів матриці

In [112]:
np.mean (matrix)

np.float64(2.5555555555555554)

7. Знайти матрицю, що складена з квадратних коренів

In [113]:
sqrt_matrix = np.sqrt(matrix)
print("Матриця квадратних коренів:")
print(sqrt_matrix)

Матриця квадратних коренів:
[[1.         1.         1.41421356]
 [1.41421356 1.41421356 1.41421356]
 [2.         2.23606798 2.        ]]


8. Обчислити суму елементів кожного рядка. Відповідь записати як вектор-стовпчик

In [114]:
row_sums = np.sum(matrix, axis=1).reshape(-1, 1)
print("Сума елементів кожного рядка:")

print(row_sums)
#В результаті отримали вектор стовпчик

Сума елементів кожного рядка:
[[ 4]
 [ 6]
 [13]]


In [115]:
matrix.sum(axis=1).reshape(-1, 1)

array([[ 4],
       [ 6],
       [13]])

In [116]:
x = np.matrix([[1, 2], [4, 3]])
x

matrix([[1, 2],
        [4, 3]])

In [117]:
x.sum(axis=1)

matrix([[3],
        [7]])

In [118]:
x.sum(axis=1, dtype='float')

matrix([[3.],
        [7.]])

9. Створити вектор, що містить 25 елементів. Заповнити числами від 0 до 9. Відсортувати числа за спаданням.

In [119]:
vector = np.random.randint(0, 10, size=25)
vector

array([1, 7, 9, 8, 5, 5, 5, 0, 4, 9, 0, 9, 1, 5, 4, 0, 5, 3, 0, 8, 5, 7,
       9, 6, 6])

In [120]:

sorted_vector = np.sort(vector) [::-1]
sorted_vector

array([9, 9, 9, 9, 8, 8, 7, 7, 6, 6, 5, 5, 5, 5, 5, 5, 4, 4, 3, 1, 1, 0,
       0, 0, 0])

10. Знайти моду, медіану, середнє, максимальне, мінімальне значення

In [121]:
from scipy import stats
# Знаходимо моду
mode = stats.mode(vector)
# Знаходимо медіану
median = np.median(vector)
# Знаходимо середнє
mean = np.mean(vector)
# Знаходимо максимальне значення
max_value = np.max(vector)
# Знаходимо мінімальне значення
min_value = np.min(vector)
print("Мода:", mode)
print("Медіана:", median)
print("Середнє:", mean)
print("Максимальне значення:", max_value)
print("Мінімальне значення:", min_value)

Мода: ModeResult(mode=np.int64(5), count=np.int64(6))
Медіана: 5.0
Середнє: 4.84
Максимальне значення: 9
Мінімальне значення: 0


11. Створити дві матриці 4*4, заповнені числами від 1 до 10. Обчислити суму, різницю, поелементний добуток, частку.

In [122]:
# Створюємо дві матриці 4х4 із випадкових цілих чисел від 1 до 10
matrix1= np.random.randint(1, 11, size=(4, 4))
matrix2 = np.random.randint(1, 11, size=(4, 4))
print("Матриця 1:")
print(matrix1)
print("\nМатриця 2:")
print(matrix2)

Матриця 1:
[[1 4 1 9]
 [2 6 7 3]
 [5 7 2 3]
 [8 9 8 5]]

Матриця 2:
[[5 8 6 3]
 [2 7 4 9]
 [5 7 7 1]
 [8 3 6 3]]


In [123]:
# Обчислюємо суму матриць
matrix_sum = matrix1 + matrix2
# Обчислюємо різницю матриць
matrix_diff = matrix1- matrix2
# Обчислюємо поелементний добуток матриць
matrix_product= matrix1*matrix2
# Обчислюємо поелементну частку матриць
# Для запобігання ділення на нуль, використовуємо пр.divide з параметром where matrix_division = np.divide (matrix1, matrix2, where=(matrix2!=0))
print("\nСума матриць:")
print(matrix_sum)
print("\nРізниця матриць:")
print(matrix_diff)
print("\nПоелементний добуток матриць:")
print(matrix_product)


Сума матриць:
[[ 6 12  7 12]
 [ 4 13 11 12]
 [10 14  9  4]
 [16 12 14  8]]

Різниця матриць:
[[-4 -4 -5  6]
 [ 0 -1  3 -6]
 [ 0  0 -5  2]
 [ 0  6  2  2]]

Поелементний добуток матриць:
[[ 5 32  6 27]
 [ 4 42 28 27]
 [25 49 14  3]
 [64 27 48 15]]


12. Задати вектор-рядок, що містить дійсні числа 1.0-8.0. Зробити матрицю 3*3. Помножити на вектор-рядок, що містить числа 0.0-2.0

In [124]:
x = np.arange(9.)
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8.])

In [125]:
x1 = x.reshape((3, 3))
x1

array([[0., 1., 2.],
       [3., 4., 5.],
       [6., 7., 8.]])

In [126]:
x2= np.arange(3.)
x2

array([0., 1., 2.])

In [127]:
#Операція трансляції векторів
np.multiply(x1, x2)

array([[ 0.,  1.,  4.],
       [ 0.,  4., 10.],
       [ 0.,  7., 16.]])

13. Задати вектор-рядок (числа 1-5). Обчислити вектор в кубі.

In [128]:
x1 = np.arange(6)
x1

array([0, 1, 2, 3, 4, 5])

In [129]:
np.power (x1, 3)

array([  0,   1,   8,  27,  64, 125])

14. Піднести до ступеня

In [44]:
x2= np.array([1, 2, 3, 3, 2, 1])
x1 = np.arange(6)
x1 ** x2

array([ 0,  1,  8, 27, 16,  5])

#**Частина** 2

1. Задати вектор, що складається з перших п'яти натуральних чисел.

In [45]:
vector = np.array([1, 2, 3, 4, 5])
vector

array([1, 2, 3, 4, 5])

2. Транспонувати вектор.

In [46]:
v1= np.matrix([1, 2, 3, 4, 5])
v1

matrix([[1, 2, 3, 4, 5]])

In [47]:
v2 = v1.T
v2

matrix([[1],
        [2],
        [3],
        [4],
        [5]])

3. Напишіть функцію, яка перевертає вектор у зворотному порядку

In [48]:
v = np.array([1, 2, 3, 4, 5])
v

array([1, 2, 3, 4, 5])

In [49]:
v[::-1]

array([5, 4, 3, 2, 1])

In [52]:
v = np.flip(v)

v

array([5, 4, 3, 2, 1])

7. Обчислити середнє значення вектора

In [53]:
np.mean(v)

np.float64(3.0)

8.Знайти найбільший і найменший елементи вектора

In [54]:
np.max(v)

np.int64(5)

In [55]:
np.min(v)

np.int64(1)

9.Обчислити скалярний добуток (dot product) двох векторів

In [57]:
v1= np.array([1, 2, 3])
v2 = np.array([4, 5, 6])


In [58]:
v1

array([1, 2, 3])

In [59]:
v2

array([4, 5, 6])

In [60]:
np.dot(v1, v2)

np.int64(32)

10. Напишіть функцію, яка нормалізує вектор (зводить до одиничної довжини).

In [62]:
v = np.array([1, 2, 3, 4, 5])
norm = np.linalg.norm(v)
print(norm)
v/norm

7.416198487095663


array([0.13483997, 0.26967994, 0.40451992, 0.53935989, 0.67419986])

11. Задайте два вектори. Визначте, чи є вони ортогональними. Підказка: якщо скалярний добуток дорівнює нулю, вектори ортогональні

In [63]:
v1 = np.array([1, 0, 0])
v2 = np.array([0, 1, 0])
np.dot(v1, v2)
#вектори ортогональні

np.int64(0)

12. Визначити унікальні елементи вектора

In [64]:
v = np.array([1, 2, 3, 2, 4, 5, 3])
np.unique(v)

array([1, 2, 3, 4, 5])

13. Знайти вектор, що є різницею між двома векторами

In [67]:
v1= np.array([1, 2, 3])
v2 = np.array([4, 5, 6])
print(v1-v2)
print(v2-v1)
print(v1 + v2)
print(v2 + v1)
print(v1*v2)
print(v2*v1)
print(v1 / v2)
print(v2 / v1)

[-3 -3 -3]
[3 3 3]
[5 7 9]
[5 7 9]
[ 4 10 18]
[ 4 10 18]
[0.25 0.4  0.5 ]
[4.  2.5 2. ]


14. Перевірити, чи дорівнює довжина вектора 5

In [68]:

vector= np.array ([1, 2, 3, 4, 5])
length = np.linalg.norm(vector)
length

np.float64(7.416198487095663)

In [69]:
np.isclose (length, 5)
#не дорівнює

np.False_

15. Задати матрицю, заповнену випадковими числами

In [70]:
a = np.random.randint(0, 11, (3, 3))
a

array([[ 8,  0,  3],
       [10,  5,  1],
       [ 0,  1,  3]])

16. Обчислити визначник матриці

In [71]:
np.linalg.det (a)

np.float64(142.00000000000003)

17. Знаходження оберненої матриці

In [72]:
np.linalg.inv(a)

array([[ 0.09859155,  0.02112676, -0.1056338 ],
       [-0.21126761,  0.16901408,  0.15492958],
       [ 0.07042254, -0.05633803,  0.28169014]])

18. Розв'яжіть систему лінійних рівнянь A-x=b, де А матриця коефіцієнтів, в вектор вільних членів.

In [92]:
a = np.array([[1, 3, -4], [0, 2, -3], [-2, 2, 5]])
b= np.array([5, 3, 4])
x= np.linalg.solve(a, b)
print('Вбудована функція', x.round(1))

inv_a= np.linalg.inv(a)
x1 = inv_a.dot(b)
print('Матричний метод', x1.round(1))

Вбудована функція [0.4 1.8 0.2]
Матричний метод [0.4 1.8 0.2]


20. Транспонування матриці

In [90]:
print(a.T)
print(b.T)

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


In [91]:
print(np.transpose(a))
print(np.transpose(b))

[[ 1  0 -2]
 [ 3  2  2]
 [-4 -3  5]]
[5 3 4]


21. Перевірка симетричності матриці

In [89]:
matrix = np.matrix ([[2, 2,2], [2, 2, 2], [2,2,2]])
np.allclose(matrix, matrix.T)

True

22. Обчислення сліду матриці

In [93]:
np.trace(matrix)

np.int64(6)

23. Сума матриць

In [94]:
a = np.matrix ([[1, 2], [3, 4]])
b=np.matrix ([[5, 6], [7, 8]])
print(np.add(a, b))
print(np.subtract(a, b))
print(np.multiply(a, b))
print(np.divide(a, b))

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


25. Сортування рядків або стовпців матриці

In [96]:
b=np.matrix ([[5, 3, 4], [2, 3, 5], [3, 2, 3]])
print(b)
print(np.sort(b, axis=0))
print(np.sort(b, axis=1))
print(np.sort(b, axis=None))

[[5 3 4]
 [2 3 5]
 [3 2 3]]
[[2 2 3]
 [3 3 4]
 [5 3 5]]
[[3 4 5]
 [2 3 5]
 [2 3 3]]
[[2 2 3 3 3 3 4 5 5]]


In [98]:
a = np.array([[1,4], [3,1]])

print(a)
print(np.sort(a))

[[1 4]
 [3 1]]
[[1 4]
 [1 3]]
